# Generated by Django 5.2.13 on 2026-05-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_name_alter_student_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
    ]
