# Generated by Django 5.2.13 on 2026-05-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
