# Generated by Django 5.2.13 on 2026-05-20 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_create_at_attendance_created_at_and_more'),
        ('students', '0003_rename_name_student_student_name'),
        ('teachers', '0005_teacher_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.teacher'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_attendance_per_day'),
        ),
    ]
